<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE concesionario [
    <!ELEMENT concesionario (modelo)*>
    <!ELEMENT modelo (#PCDATA|motor|potencia|consumo_medio)*>
    <!ATTLIST modelo
        id ID #REQUIRED
        modelos_relacionados IDREFS #IMPLIED
    >
    <!ELEMENT motor (#PCDATA)>
    <!ATTLIST motor modelos_relacionados IDREFS #REQUIRED>
    <!ELEMENT potencia (#PCDATA)>
    <!ELEMENT consumo_medio (#PCDATA)>
    <!ATTLIST consumo_medio kmh CDATA #REQUIRED>
]>

<concesionario>
    <modelo id="M556">No disponible</modelo>
    <modelo id="M555" modelos_relacionados="M444 M556">
        Este modelo tiene un
        <motor modelos_relacionados="M556">1.998cc 16v. de cuatro cilindros</motor>
        que desarrolla una potencia de
        <potencia>128</potencia>
        CV. Dispone de cambio manual ... el consumo medio de este monovolumen es
        <consumo_medio kmh="100">11</consumo_medio>
        a los 100 km. El precio base es de 2.225.000.
    </modelo>
    <modelo id="M557">No disponible</modelo>
    <modelo id="M154">No disponible</modelo>
    <modelo id="M444" modelos_relacionados="M555 M154">
        Este modelo tiene un
        <motor modelos_relacionados="M556">2.000cc 16v. de cuatro cilindros</motor>
        con
        <potencia>128</potencia>
        CV. Dispone de cambio manual ... el consumo medio de este monovolumen es
        <consumo_medio kmh="100">11</consumo_medio>
        a los 100 km. El precio base es de 2.500.000.
    </modelo>
</concesionario>