=== LordKradical/XML-clase/xml-relacion/Relación 4/cd.dtd
<!ELEMENT cd (fecha, canciones)>
<!ATTLIST cd titulo NMTOKENS #REQUIRED>
<!ELEMENT fecha EMPTY>
<!ATTLIST fecha dia CDATA #REQUIRED>
<!ATTLIST fecha mes CDATA #REQUIRED>
<!ATTLIST fecha anio CDATA #REQUIRED>
<!ELEMENT canciones (cancion+)>
<!ELEMENT cancion (titulo, compositores, productores, sello, artista)>
<!ATTLIST cancion duracion CDATA #REQUIRED>
<!ATTLIST cancion anio CDATA #REQUIRED>
<!ATTLIST cancion precio (0.99|1.49|1.99) #REQUIRED>
<!ATTLIST cancion moneda (dolar|euro) "euro">
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT compositores (compositor+)>
<!ELEMENT compositor (nombres, apellidos)>
<!ELEMENT productores (productor+)>
<!ELEMENT productor (nombres, apellidos)>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT sello (#PCDATA)>
<!ELEMENT artista (#PCDATA)>

=== LordKradical/XML-clase/xml-relacion/Relación 4/Ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cd SYSTEM "cd.dtd">

<cd titulo="Titulo">
    <fecha dia="2" mes="2" anio="2008" />
    <canciones>
        <cancion duracion="4:47" anio="2008" precio="0.99">
            <titulo>Give it 2 me</titulo>
            <compositores>
                <compositor>
                    <nombres>Pharrell</nombres>
                    <apellidos>Williams</apellidos>
                </compositor>
            </compositores>
            <productores>
                <productor>
                    <nombres>Pharrell</nombres>
                    <apellidos>Williams</apellidos>
                </productor>
            </productores>
            <sello>Warner Bros. Records</sello>
            <artista>Madonna</artista>
        </cancion>
    </canciones>
</cd>
