<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE agenda [
    <!ELEMENT agenda (contacto*)>
    <!ELEMENT contacto (nombre, apellido+, telefono, email, direccion)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ATTLIST telefono pais CDATA #REQUIRED>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT direccion (calle, numero, cp)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT cp (#PCDATA)>
]>

<agenda>
    <contacto>
        <nombre>Javier</nombre>
        <apellido>Fernández</apellido>
        <apellido>Gil</apellido>
        <telefono pais="España">954000000</telefono>
        <email>fergil@asir.es</email>
        <direccion>
            <calle>calle Perseo </calle>
            <numero>4</numero>
            <cp>41020</cp>
        </direccion>
    </contacto>
</agenda>