<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE libreria [
    <!ELEMENT libreria (libro*)>
    <!ELEMENT libro (isbn, titulo, autor*, editorial, precio)>
    <!ELEMENT isbn (#PCDATA)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT editorial (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
]>

<libreria>
    <libro>
        <isbn>978-84</isbn>
        <titulo>Lenguaje de Marcas</titulo>
        <autor>Javier Zurdo</autor>
        <autor>Laura Raya</autor>
        <editorial>Ra-ma</editorial>
        <precio>23</precio>
    </libro>
    <libro>
        <isbn>657-81</isbn>
        <titulo>Introducción a XML</titulo>
        <editorial>Sol</editorial>
        <precio>15</precio>
    </libro>
    <libro>
        <isbn>544-73</isbn>
        <titulo>Aplicaciones Web</titulo>
        <autor>David Roldán</autor>
        <autor>Pedro Valderas</autor>
        <editorial>Ra-ma</editorial>
        <precio>44</precio>
    </libro>
</libreria>